M48
; DRILL file {KiCad 8.0.3} date 2024-07-23T23:43:31-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-23T23:43:31-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1614
%
G90
G05
T1
X6.0795Y-4.7292
X6.13Y-2.8321
X6.3295Y-4.6292
X6.38Y-2.7321
T2
X6.2295Y-4.8292
X6.23Y-2.6321
M30
